[package]
name = "lpda_beam_healpix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
necrs={path='../necrs'}
scorus={path='../scorus'}
num='0.4.0'
pest = '2.1.3'
pest_derive='2.1.0'


[dependencies.healpix_fits]
path = '../healpix_fits'
