[dependencies]
clap = '3.0.6'
num = '0.4.0'
pest = '2.1.3'
pest_derive = '2.1.0'
serde_yaml = '0.8.21'


[dependencies.serde]
features = ['derive']
version = '1.0.130'

[dependencies.healpix_fits]
path = '../healpix_fits'

[dependencies.necrs]
path = '../necrs'

[dependencies.scorus]
path = '../scorus'

[package]
edition = '2021'
name = 'dbf_beam_simulator'
version = '0.1.0'
